# Generated by Django 5.0.6 on 2024-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=256)),
                ('clothes', models.CharField(max_length=256)),
                ('electronic', models.CharField(max_length=256)),
                ('for_home', models.CharField(max_length=256)),
                ('car', models.CharField(max_length=256)),
                ('mobile', models.CharField(max_length=256)),
                ('apartment', models.CharField(max_length=256)),
                ('travelling', models.CharField(max_length=256)),
                ('medical', models.CharField(max_length=256)),
                ('gifts', models.CharField(max_length=256)),
                ('transfer', models.CharField(max_length=256)),
                ('saves', models.CharField(max_length=256)),
            ],
        ),
    ]
